# Generated by Django 5.2.8 on 2025-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="managerprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
