# Generated by Django 5.2.8 on 2025-11-06 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_employeeprofile_id_alter_managerprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 11, 17, 26, 964093, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
