# Generated by Django 5.2.8 on 2025-11-06 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="create_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="create_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 11, 32, 53, 184836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
