# Generated by Django 5.2.8 on 2025-11-06 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_employeeprofile_create_id_managerprofile_create_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 11, 42, 22, 38316, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
