# Generated by Django 5.2.8 on 2025-11-06 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 11, 43, 29, 70957, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
