# Generated by Django 5.2.8 on 2025-11-06 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="create_id",
        ),
        migrations.RemoveField(
            model_name="managerprofile",
            name="create_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="create_id",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 11, 43, 44, 202467, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
