# Generated by Django 5.2.8 on 2025-11-06 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_employeeprofile_create_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 12, 39, 45, 171312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
