# Generated by Django 5.2.8 on 2025-11-06 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 12, 57, 40, 76077, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
