# Generated by Django 5.2.8 on 2025-11-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 13, 21, 6, 244718, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
