# Generated by Django 5.2.8 on 2025-11-07 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 14, 7, 25, 34, 626040, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
