# Generated by Django 5.2.8 on 2025-11-07 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 14, 8, 46, 32, 303267, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
