# Generated by Django 5.2.8 on 2025-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_task_assigned_to_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
